# codemagic.yaml
# Documentação: https://docs.codemagic.io/yaml-basic-configuration/configuring-workflows/

workflows:
  android-release-build:
    name: Android Release Build

    environment:
      flutter: stable  # Ou especifique uma versão como "3.19.6"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - allangoncalves004@gmail.com
        notify:
          success: true
          failure: true

