name: peladao
description: Peladão V2.0
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
